import image from "../../images/temp.jpg"
const transactionData = [
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "report 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 2",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "report 2",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "report 3",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "Report 4",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Prescription",
    description: "Prescription 1",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "Report 5",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "Report 6",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "Report 7",
    doctor: "Dr. Sneha",
  },
  {
    img: image,
    date: "29 July 2023",
    type: "Report",
    description: "Report 8",
    doctor: "Dr. Sneha",
  },
];

export default transactionData;
